---
apiVersion: v1
kind: Service
metadata:
    name: {{ required "Please specify a 'name' in the user file" .Values.name }}
    namespace: {{ required "Please specify a 'namespace' in the user file" .Values.namespace }}
spec:
    type: ClusterIP
    selector:
        deployment.apps: susql-controller
    ports:
        - name: metrics
          port: 8082
          targetPort: 8082
          protocol: TCP
