#!/bin/bash

# usage command -n "comma,delimited,list,of,namespaces" to limit to specified namespaces
# usage command to display SusQL energy data on all namespaces that have such data

if [[ ${#} -gt 1 && ${1} -eq '-n' ]]
then
	ns=$(echo ${2} | tr ',' ' ')
else
	ns=$(oc projects -q)
fi

printf  '%-20s%-40s%-40s%-20s\n' NameSpace LabelGroup Labels TotalEnergy

for namespace in ${ns}
do
    for labelgroup in $(kubectl -n ${namespace} get labelgroups -o custom-columns=':{.metadata.name}')
    do
        totalEnergy=$(kubectl -n ${namespace} get labelgroup ${labelgroup} -o jsonpath='{.status.totalEnergy}')
        labels=$(kubectl -n ${namespace} get labelgroup ${labelgroup} -o jsonpath='{.spec.labels}')
        printf '%-20s%-40s%-40s%-20s\n' ${namespace} ${labelgroup} ${labels} ${totalEnergy}
    done
done | sort -nr -k4 | head -n 20
