---
apiVersion: v1
kind: Pod
metadata:
  name: impact-framework
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: container
    image: quay.io/trent_s/impact-framework
    imagePullPolicy: Always
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - "ALL"
    command: ["/bin/sh", "-c"]
    args:
      - sleep infinity;
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
