apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: susql-controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: susql-operator
    app.kubernetes.io/part-of: susql-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: susql-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: susql-controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: susql-operator
    app.kubernetes.io/created-by: susql-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: susql-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: susql-controller-manager
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. OpenShift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        # - /debug-entrypoint.sh
        env:
          - name: KEPLER-PROMETHEUS-URL
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: KEPLER-PROMETHEUS-URL
                optional: true
          - name: KEPLER-METRIC-NAME
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: KEPLER-METRIC-NAME
                optional: true
          - name: SUSQL-PROMETHEUS-DATABASE-URL
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: SUSQL-PROMETHEUS-DATABASE-URL
                optional: true
          - name: SUSQL-PROMETHEUS-METRICS-URL
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: SUSQL-PROMETHEUS-METRICS-URL
                optional: true
          - name: SAMPLING-RATE
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: SAMPLING-RATE
                optional: true
          - name: LEADER-ELECT
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: LEADER-ELECT
                optional: true
          - name: HEALTH-PROBE-BIND-ADDRESS
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: HEALTH-PROBE-BIND-ADDRESS
                optional: true
          - name: SUSQL-LOG-LEVEL
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: SUSQL-LOG-LEVEL
                optional: true
          - name: CARBON-METHOD
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-METHOD
                optional: true
          - name: CARBON-INTENSITY
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-INTENSITY
                optional: true
          - name: CARBON-INTENSITY-URL
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-INTENSITY-URL
                optional: true
          - name: CARBON-LOCATION
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-LOCATION
                optional: true
          - name: CARBON-QUERY-RATE
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-QUERY-RATE
                optional: true
          - name: CARBON-QUERY-FILTER
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-QUERY-FILTER
                optional: true
          - name: CARBON-QUERY-CONV-2J
            valueFrom:
              configMapKeyRef:
                name: susql-config
                key: CARBON-QUERY-CONV-2J
                optional: true
        image: '<OPERATOR_IMG>'
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem : true
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        ports:
        - containerPort: 8082
          protocol: TCP
          name: metric
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
      serviceAccountName: susql-controller-manager
      terminationGracePeriodSeconds: 10
