---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - susql.ibm.com
  resources:
  - labelgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - susql.ibm.com
  resources:
  - labelgroups/finalizers
  verbs:
  - update
- apiGroups:
  - susql.ibm.com
  resources:
  - labelgroups/status
  verbs:
  - get
  - patch
  - update
