apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: susql-operator
    app.kubernetes.io/instance: susql-controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: susql-operator
    app.kubernetes.io/part-of: susql-operator
    app.kubernetes.io/managed-by: kustomize
  name: susql-controller-manager
  namespace: system
