name: Build and Publish Images
description: "Publishes operator and bundle images to an Image Registry"
inputs:
  image_registry:
    description: "image registry"
    required: true
  image_url:
    description: "url to image in registry"
    required: true
  registry_login:
    description: "registry username"
    required: true
  registry_token:
    description: "registry token"
    required: true

  version:
    description: "operator version"
    required: true

  additional_tags:
    description: "additional tags for container images"
    required: false
runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
        cache: true

    - name: Login to Image Registry
      uses: redhat-actions/podman-login@v1
      if: "!startsWith(inputs.image_registry, 'localhost')"
      with:
        registry: ${{ inputs.image_registry }}
        username: ${{ inputs.registry_login }}
        password: ${{ inputs.registry_token }}

    - name: Build Operator and image and then push
      shell: bash
      run: |
        make operator-build && make operator-push
      env:
        VERSION: ${{ inputs.version }}
        OPERATOR_IMG: ${{ format('{0}', inputs.image_url) }}
        ADDITIONAL_TAGS: ${{ inputs.additional_tags }}
