---
apiVersion: v1
kind: Pod
metadata:
    name: kepler-check
spec:
    automountServiceAccountToken: true
    terminationGracePeriodSeconds: 1
    restartPolicy: Never
    securityContext:
        runAsUser: 10001
        runAsGroup: 10001
    containers:
        - name: container
          image: curlimages/curl
          imagePullPolicy: IfNotPresent
          securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              readOnlyRootFilesystem: true
              capabilities:
                  drop:
                      - "ALL"
          resources:
              limits:
                  cpu: 500m
                  memory: 512Mi
              requests:
                  cpu: 250m
                  memory: 512Mi
          command: ["sh"]
          args: ["-c", 'curl -k --max-time 1 SOURCE_PROMETHEUS_URL -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"']
    dnsPolicy: ClusterFirst
    serviceAccount: prometheus-k8s
    serviceAccountName: prometheus-k8s
