name: Publish Images

on:
  push:
    branches: [ main, etcd-double-count-bug ]

jobs:
  publish:
      if: github.repository_owner == 'sustainable-computing-io'
      name: Publish operator container images
      environment: SusQL-Environment
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source
          uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version-file: go.mod

        - uses: ./.github/compute-version
          id: version

        - name: additional tags
          id: additional_tags
          shell: bash
          run: |
            echo "result=$(git rev-parse --short HEAD),main" >> $GITHUB_OUTPUT

        - name: build and publish images to external registry
          uses: ./.github/publish-images
          with:
            image_url: ${{ vars.IMG }}
            image_registry: ${{ vars.REGISTRY }}
            registry_login: ${{ secrets.QUAY_BOT_NAME }}
            registry_token: ${{ secrets.QUAY_BOT_TOKEN }}
            version: ${{ steps.version.outputs.version }}
            additional_tags: ${{ steps.additional_tags.outputs.result }}
